Reply all | 
Delete
Junk | 


mcr script

Moustafa Mahmoud Mahmoud
Reply all | 


Today, 1:20 PM
Moustafa Mahmoud Mahmoud;
Moustafa Mahmoud <mmahmoud2@learn.athabascau.ca>
...

Inbox
Inbox
--------------------------------------------------------

--  File created - Monday-September-04-2023  

--------------------------------------------------------

--------------------------------------------------------

--  DDL for Table NCIB_101_CUSTOMER_PERMISIONS

--------------------------------------------------------

 

  CREATE TABLE "NCIB_101_CUSTOMER_PERMISIONS"

   (           "CUSTOMER_CIF" VARCHAR2(40 BYTE),

                "PERMISSION_NAME" VARCHAR2(255 BYTE)

   ) SEGMENT CREATION IMMEDIATE

  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255

 NOCOMPRESS LOGGING

  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645

  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1

  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)

  TABLESPACE "SI_DATA" ;

--------------------------------------------------------

--  DDL for Table NCIB_102_CUSTOMER_PERMISSIONS_PER_ACCOUNT

--------------------------------------------------------

 

  CREATE TABLE "NCIB_102_CUSTOMER_PERMISSIONS_PER_ACCOUNT"

   (           "CUSTOMER_CIF" VARCHAR2(40 BYTE),

                "PERMISSION_NAME" VARCHAR2(255 BYTE),

                "ACCOUNT_NUMBER" VARCHAR2(48 BYTE)

   ) SEGMENT CREATION IMMEDIATE

  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255

 NOCOMPRESS LOGGING

  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645

  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1

  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)

  TABLESPACE "SI_DATA" ;

--------------------------------------------------------

--  DDL for Table NCIB_103_DIVISIONS_PERMISSIONS

--------------------------------------------------------

 

  CREATE TABLE "NCIB_103_DIVISIONS_PERMISSIONS"

   (           "BUSINESS_CIF" VARCHAR2(40 BYTE),

                "MCR_USER_GROUP_ID" VARCHAR2(32 BYTE),

                "DIVISION_NAME" VARCHAR2(988 BYTE),

                "OPERATION_NAME" VARCHAR2(255 BYTE)

   ) SEGMENT CREATION IMMEDIATE

  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255

 NOCOMPRESS LOGGING

  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645

  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1

  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)

  TABLESPACE "SI_DATA" ;

--------------------------------------------------------

--  DDL for Table NCIB_104_DIVISIONS_PERMISIONS_PER_ACCOUNT

--------------------------------------------------------

 

  CREATE TABLE "NCIB_104_DIVISIONS_PERMISIONS_PER_ACCOUNT"

   (           "CIF" VARCHAR2(40 BYTE),

                "MCR_USER_GROUP_ID" VARCHAR2(32 BYTE),

                "DIVISION_NAME" VARCHAR2(988 BYTE),

                "OPERATION_NAME" VARCHAR2(255 BYTE),

                "ACCOUNT_NUMBER" VARCHAR2(48 BYTE)

   ) SEGMENT CREATION IMMEDIATE

  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255

 NOCOMPRESS LOGGING

  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645

  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1

  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)

  TABLESPACE "SI_DATA" ;

--------------------------------------------------------

--  DDL for Table NCIB_105_USER_PERMISSIONS

--------------------------------------------------------

 

  CREATE TABLE "NCIB_105_USER_PERMISSIONS"

   (           "CIF" VARCHAR2(40 BYTE),

                "MCR_USER_ID" VARCHAR2(21 BYTE),

                "PERMISSION_NAME" VARCHAR2(255 BYTE)

   ) SEGMENT CREATION IMMEDIATE

  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255

 NOCOMPRESS LOGGING

  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645

  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1

  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)

  TABLESPACE "SI_DATA" ;

--------------------------------------------------------

--  DDL for Table NCIB_106_USER_PERMISSIONS_PER_ACCOUNT

--------------------------------------------------------

 

  CREATE TABLE "NCIB_106_USER_PERMISSIONS_PER_ACCOUNT"

   (           "CIF" VARCHAR2(40 BYTE),

                "MCR_USER_ID" VARCHAR2(21 BYTE),

                "PERMISSION_NAME" VARCHAR2(255 BYTE),

                "ACCOUNT_NUMBER" VARCHAR2(48 BYTE)

   ) SEGMENT CREATION IMMEDIATE

  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255

 NOCOMPRESS LOGGING

  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645

  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1

  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)

  TABLESPACE "SI_DATA" ;

--------------------------------------------------------

--  DDL for Table NCIB_107_ACCOUNT_ACCESS_CUSTOMER_LEVEL

--------------------------------------------------------

 

  CREATE TABLE "NCIB_107_ACCOUNT_ACCESS_CUSTOMER_LEVEL"

   (           "CIF" VARCHAR2(40 BYTE),

                "ACCOUNT_OR_BENEFICIARY" VARCHAR2(10 BYTE),

                "ACCOUNT_NUMBER" VARCHAR2(48 BYTE)

   ) SEGMENT CREATION IMMEDIATE

  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255

 NOCOMPRESS LOGGING

  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645

  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1

  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)

  TABLESPACE "SI_DATA" ;

--------------------------------------------------------

--  DDL for Table NCIB_107_ACCOUNT_ACCESS_DIVISION_LEVEL

--------------------------------------------------------

 

  CREATE TABLE "NCIB_107_ACCOUNT_ACCESS_DIVISION_LEVEL"

   (           "BUSINESS_CIF" VARCHAR2(40 BYTE),

                "MCR_USER_GROUP_ID" VARCHAR2(32 BYTE),

                "DIVISION_NAME" VARCHAR2(988 BYTE),

                "ACCOUNT_OR_BENEFICIARY" VARCHAR2(10 BYTE),

                "ACCOUNT_NUMBER" VARCHAR2(48 BYTE)

   ) SEGMENT CREATION IMMEDIATE

  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255

 NOCOMPRESS LOGGING

  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645

  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1

  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)

  TABLESPACE "SI_DATA" ;

--------------------------------------------------------

--  DDL for Table NCIB_107_ACCOUNT_ACCESS_USER_LEVEL

--------------------------------------------------------

 

  CREATE TABLE "NCIB_107_ACCOUNT_ACCESS_USER_LEVEL"

   (           "CIF" VARCHAR2(40 BYTE),

                "MCR_USER_ID" VARCHAR2(21 BYTE),

                "ACCOUNT_OR_BENEFICIARY" VARCHAR2(16 BYTE),

                "ACCOUNT_NUMBER" VARCHAR2(48 BYTE)

   ) SEGMENT CREATION IMMEDIATE

  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255

 NOCOMPRESS LOGGING

  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645

  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1

  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)

  TABLESPACE "SI_DATA" ;

--------------------------------------------------------

--  DDL for Table NCIB_109_APPROVAL_GROUPS

--------------------------------------------------------

 

  CREATE TABLE "NCIB_109_APPROVAL_GROUPS"

   (           "CIF" VARCHAR2(40 BYTE),

                "GROUP_NAME" VARCHAR2(255 BYTE),

                "MCR_USER_ID" VARCHAR2(20 BYTE)

   ) SEGMENT CREATION IMMEDIATE

  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255

 NOCOMPRESS LOGGING

  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645

  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1

  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)

  TABLESPACE "SI_DATA" ;

--------------------------------------------------------

--  DDL for Table NCIB_110_SPRINT4_LIMIT_STRUCTURE

--------------------------------------------------------

 

  CREATE TABLE "NCIB_110_SPRINT4_LIMIT_STRUCTURE"

   (           "INTERNAL_ID" NUMBER,

                "PERMISSION_NAME" VARCHAR2(255 BYTE),

                "AMOUNT" VARCHAR2(30 BYTE),

                "CURRENCY_CODE" CHAR(3 BYTE),

                "ALLOWAPPROVAL" CHAR(1 BYTE),

                "LIMIT_PERIOD" VARCHAR2(40 BYTE)

   ) SEGMENT CREATION IMMEDIATE

  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255

 NOCOMPRESS LOGGING

  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645

  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1

  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)

  TABLESPACE "SI_DATA" ;

--------------------------------------------------------

--  DDL for Table NCIB_111_SERVICE_PACKAGE_PERMISSIONS

--------------------------------------------------------

 

  CREATE TABLE "NCIB_111_SERVICE_PACKAGE_PERMISSIONS"

   (           "OPERATION_NAME" VARCHAR2(255 BYTE),

                "SERVICE_PACKAGE_NAME" VARCHAR2(255 BYTE)

   ) SEGMENT CREATION IMMEDIATE

  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255

 NOCOMPRESS LOGGING

  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645

  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1

  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)

  TABLESPACE "SI_DATA" ;

--------------------------------------------------------

--  DDL for Table NCIB_111_SPRINT4_SERVICE_PACKAGE_LIMIT

--------------------------------------------------------

 

  CREATE TABLE "NCIB_111_SPRINT4_SERVICE_PACKAGE_LIMIT"

   (           "SERVICE_PACKAGE_INTERNAL_ID" NUMBER(38,0),

                "OPERATION_NAME" VARCHAR2(255 BYTE),

                "AMOUNT" VARCHAR2(30 BYTE),

                "CURRENCY_CODE" CHAR(3 BYTE),

                "ALLOWAPPROVAL" CHAR(1 BYTE),

                "SERVICE_PACKAGE_NAME" VARCHAR2(255 BYTE),

                "LIMIT_PERIOD" VARCHAR2(40 BYTE)

   ) SEGMENT CREATION IMMEDIATE

  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255

 NOCOMPRESS LOGGING

  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645

  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1

  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)

  TABLESPACE "SI_DATA" ;

--------------------------------------------------------

--  DDL for Table NCIB_113_SPRINT4_LIMITS_CUSTOMER

--------------------------------------------------------

 

  CREATE TABLE "NCIB_113_SPRINT4_LIMITS_CUSTOMER"

   (           "CIF" VARCHAR2(40 BYTE),

                "OPERATION_NAME" VARCHAR2(255 BYTE),

                "LIMIT_PERIOD" VARCHAR2(40 BYTE),

                "LIMIT_AMOUNT" VARCHAR2(30 BYTE),

                "ALLOW_APPROVAL" CHAR(1 BYTE),

                "CURRENCYCODE" CHAR(3 BYTE)

   ) SEGMENT CREATION IMMEDIATE

  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255

 NOCOMPRESS LOGGING

  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645

  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1

  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)

  TABLESPACE "SI_DATA" ;

--------------------------------------------------------

--  DDL for Table NCIB_114_SPRINT4_LIMITS_CUSTOMER_PER_ACCOUNT

--------------------------------------------------------

 

  CREATE TABLE "NCIB_114_SPRINT4_LIMITS_CUSTOMER_PER_ACCOUNT"

   (           "CIF" VARCHAR2(40 BYTE),

                "BANKING_ACCOUNT" VARCHAR2(1020 BYTE),

                "LIMIT_PERIOD" VARCHAR2(40 BYTE),

                "LIMIT_AMOUNT" VARCHAR2(30 BYTE),

                "ALLOW_APPROVAL" CHAR(1 BYTE),

                "CURRENCY_CODE" CHAR(3 BYTE)

   ) SEGMENT CREATION IMMEDIATE

  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255

 NOCOMPRESS LOGGING

  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645

  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1

  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)

  TABLESPACE "SI_DATA" ;

--------------------------------------------------------

--  DDL for Table NCIB_114_SPRINT4_LIMITS_CUSTOMER_PER_ACCOUNT_PER_PERMISSION

--------------------------------------------------------

 

  CREATE TABLE "NCIB_114_SPRINT4_LIMITS_CUSTOMER_PER_ACCOUNT_PER_PERMISSION"

   (           "CIF" VARCHAR2(40 BYTE),

                "PERMISSION_NAME" VARCHAR2(255 BYTE),

                "OBJECT_ID" VARCHAR2(255 BYTE),

                "LIMIT_PERIOD" VARCHAR2(40 BYTE),

                "LIMIT_AMOUNT" VARCHAR2(30 BYTE),

                "ALLOW_APPROVAL" CHAR(1 BYTE),

                "CURRENCY_CODE" CHAR(3 BYTE)

   ) SEGMENT CREATION IMMEDIATE

  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255

 NOCOMPRESS LOGGING

  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645

  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1

  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)

  TABLESPACE "SI_DATA" ;

--------------------------------------------------------

--  DDL for Table NCIB_115_SPRINT4_LIMITS_DIVISION_CROSS_ACCOUNT

--------------------------------------------------------

 

  CREATE TABLE "NCIB_115_SPRINT4_LIMITS_DIVISION_CROSS_ACCOUNT"

   (           "BUSINESS_CIF" VARCHAR2(32 BYTE),

                "MCR_DIVISION_ID" VARCHAR2(32 BYTE),

                "DIVISION_NAME" VARCHAR2(988 BYTE),

                "PERMISSION_NAME" VARCHAR2(255 BYTE),

                "LIMIT_PERIOD" VARCHAR2(40 BYTE),

                "LIMIT_AMOUNT" VARCHAR2(30 BYTE),

                "ALLOW_APPROVAL" CHAR(1 BYTE),

                "CURRENCY_CODE" CHAR(3 BYTE)

   ) SEGMENT CREATION IMMEDIATE

  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255

 NOCOMPRESS LOGGING

  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645

  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1

  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)

  TABLESPACE "SI_DATA" ;

--------------------------------------------------------

--  DDL for Table NCIB_116_SPRINT4_LIMITS_DIVISION_ACCOUNT

--------------------------------------------------------

 

  CREATE TABLE "NCIB_116_SPRINT4_LIMITS_DIVISION_ACCOUNT"

   (           "BUSINESS_CIF" VARCHAR2(40 BYTE),

                "MCR_DIVISION_ID" VARCHAR2(32 BYTE),

                "DIVISION_NAME" VARCHAR2(988 BYTE),

                "BANKING_ACCOUNT" VARCHAR2(1020 BYTE),

                "LIMIT_PERIOD" VARCHAR2(40 BYTE),

                "LIMIT_AMOUNT" VARCHAR2(30 BYTE),

                "ALLOW_APPROVAL" CHAR(1 BYTE),

                "CURRENCY_CODE" CHAR(3 BYTE)

   ) SEGMENT CREATION IMMEDIATE

  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255

 NOCOMPRESS LOGGING

  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645

  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1

  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)

  TABLESPACE "SI_DATA" ;

--------------------------------------------------------

--  DDL for Table NCIB_116_SPRINT4_LIMITS_DIVISION_ACCOUNT_PERMISSION

--------------------------------------------------------

 

  CREATE TABLE "NCIB_116_SPRINT4_LIMITS_DIVISION_ACCOUNT_PERMISSION"

   (           "BUSINESS_CIF" VARCHAR2(40 BYTE),

                "MCR_DIVISION_ID" VARCHAR2(32 BYTE),

                "DIVISION_NAME" VARCHAR2(988 BYTE),

                "PERMISSION_NAME" VARCHAR2(255 BYTE),

                "BANKING_ACCOUNT" VARCHAR2(1020 BYTE),

                "LIMIT_PERIOD" VARCHAR2(40 BYTE),

                "LIMIT_AMOUNT" VARCHAR2(30 BYTE),

                "ALLOW_APPROVAL" CHAR(1 BYTE),

                "CURRENCY_CODE" CHAR(3 BYTE)

   ) SEGMENT CREATION IMMEDIATE

  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255

 NOCOMPRESS LOGGING

  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645

  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1

  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)

  TABLESPACE "SI_DATA" ;

--------------------------------------------------------

--  DDL for Table NCIB_117_SPRINT4_LIMITS_USER

--------------------------------------------------------

 

  CREATE TABLE "NCIB_117_SPRINT4_LIMITS_USER"

   (           "MCR_USER_ID" VARCHAR2(20 BYTE),

                "USER_NAME" VARCHAR2(20 BYTE),

                "CIF" VARCHAR2(40 BYTE),

                "PERMISSION_NAME" VARCHAR2(255 BYTE),

                "LIMIT_PERIOD" VARCHAR2(40 BYTE),

                "LIMIT_AMOUNT" VARCHAR2(30 BYTE),

                "ALLOW_APPROVAL" CHAR(1 BYTE),

                "CURRENCYCODE" CHAR(3 BYTE),

                "INTERNAL_USER_ID" VARCHAR2(255 BYTE)

   ) SEGMENT CREATION IMMEDIATE

  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255

 NOCOMPRESS LOGGING

  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645

  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1

  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)

  TABLESPACE "SI_DATA" ;

--------------------------------------------------------

--  DDL for Table NCIB_118_SPRINT4_LIMITS_USER_ACCOUNT

--------------------------------------------------------

 

  CREATE TABLE "NCIB_118_SPRINT4_LIMITS_USER_ACCOUNT"

   (           "MCR_USER_ID" VARCHAR2(20 BYTE),

                "USER_NAME" VARCHAR2(20 BYTE),

                "CIF" VARCHAR2(40 BYTE),

                "BANKING_ACCOUNT" VARCHAR2(1020 BYTE),

                "LIMIT_PERIOD" VARCHAR2(40 BYTE),

                "LIMIT_AMOUNT" VARCHAR2(30 BYTE),

                "ALLOW_APPROVAL" CHAR(1 BYTE),

                "CURRENCYCODE" CHAR(3 BYTE),

                "INTERNAL_USER_ID" VARCHAR2(255 BYTE)

   ) SEGMENT CREATION IMMEDIATE

  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255

 NOCOMPRESS LOGGING

  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645

  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1

  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)

  TABLESPACE "SI_DATA" ;

--------------------------------------------------------

--  DDL for Table NCIB_118_SPRINT4_LIMITS_USER_ACCOUNT_PERMISSION

--------------------------------------------------------

 

  CREATE TABLE "NCIB_118_SPRINT4_LIMITS_USER_ACCOUNT_PERMISSION"

   (           "MCR_USER_ID" VARCHAR2(20 BYTE),

                "USER_NAME" VARCHAR2(20 BYTE),

                "CIF" VARCHAR2(40 BYTE),

                "PERMISSION_NAME" VARCHAR2(255 BYTE),

                "BANKING_ACCOUNT" VARCHAR2(1020 BYTE),

                "LIMIT_PERIOD" VARCHAR2(40 BYTE),

                "LIMIT_AMOUNT" VARCHAR2(30 BYTE),

                "ALLOW_APPROVAL" CHAR(1 BYTE),

                "CURRENCY_CODE" CHAR(3 BYTE),

                "INTERNAL_USER_ID" VARCHAR2(255 BYTE)

   ) SEGMENT CREATION IMMEDIATE

  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255

 NOCOMPRESS LOGGING

  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645

  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1

  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)

  TABLESPACE "SI_DATA" ;

--------------------------------------------------------

--  DDL for Table NCIB_119_FUSION_WORKFLOW

--------------------------------------------------------

 

  CREATE TABLE "NCIB_119_FUSION_WORKFLOW"

   (           "CIF" VARCHAR2(40 BYTE),

                "APPROVALRANGEID" NUMBER(38,0),

                "MINIMUM_AMOUNT" NUMBER(31,3),

                "MAXIMUM_AMOUNT" NUMBER(31,3),

                "USER_OR_DIVISION_OR_APPROVAL_GROUP" VARCHAR2(14 BYTE),

                "MW_USERID_OR_DIVISION_NAME_OR_GROUP_NAME" VARCHAR2(32 BYTE),

                "PERMISSION_NAME" VARCHAR2(255 BYTE)

   ) SEGMENT CREATION IMMEDIATE

  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255

 NOCOMPRESS LOGGING

  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645

  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1

 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)

  TABLESPACE "SI_DATA" ;

--------------------------------------------------------

--  DDL for Table NCIB_121_SPRINT8_APPROVAL_WORKFLOW_TASKS_SADAD_BILLS

--------------------------------------------------------

 

  CREATE TABLE "NCIB_121_SPRINT8_APPROVAL_WORKFLOW_TASKS_SADAD_BILLS"

   (           "CIF" NUMBER(38,0),

                "IS_ADHOC" CHAR(1 BYTE),

                "DECISION_DATE" TIMESTAMP (6),

                "MCR_BILLER_TYPE" VARCHAR2(20 BYTE),

                "BILL_NIKENAME" VARCHAR2(200 BYTE),

                "APPROVER_MCR_ID" VARCHAR2(20 BYTE),

                "SUBMITTER_MCR_ID" VARCHAR2(20 BYTE),

                "SADAD_BILLER_ID" VARCHAR2(20 BYTE),

                "PAYMENT_TYPE" VARCHAR2(20 BYTE),

                "BILL_NUMBER" VARCHAR2(50 BYTE),

                "AMOUNT" NUMBER(31,3),

                "INTERNAL_ID" NUMBER(38,0),

                "FROM_ACCOUNT" VARCHAR2(50 BYTE),

                "APPROVAL_TASK_STATUS" VARCHAR2(10 BYTE),

                "SUBMITTION_DATE" TIMESTAMP (6),

                "IS_FAVORITE_BILL" CHAR(1 BYTE)

   ) SEGMENT CREATION IMMEDIATE

  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255

 NOCOMPRESS LOGGING

  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645

  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1

  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)

  TABLESPACE "SI_DATA" ;

--------------------------------------------------------

--  DDL for Table NCIB_122_SPRINT8_APPROVAL_WORKFLOW_TASKS_INVOICE_ISAL

--------------------------------------------------------

 

  CREATE TABLE "NCIB_122_SPRINT8_APPROVAL_WORKFLOW_TASKS_INVOICE_ISAL"

   (           "INTERNAL_ID" NUMBER,

                "INVOICE_NUMBER" VARCHAR2(50 BYTE),

                "BILLER_NAME" VARCHAR2(100 BYTE),

                "BILLER_ID" VARCHAR2(50 BYTE),

                "INVOICE_CODE" VARCHAR2(50 BYTE),

                "SUBMITTER_MCR_ID" VARCHAR2(20 BYTE),

                "DECISION_DATE" TIMESTAMP (6),

                "FROM_ACCOUNT" VARCHAR2(50 BYTE),

                "APPROVER_MCR_ID" VARCHAR2(20 BYTE),

                "APPROVAL_TASK_STATUS" VARCHAR2(50 BYTE),

                "SUBMITTION_DATE" TIMESTAMP (6),

                "INVOICE_DUE_DATE" VARCHAR2(50 BYTE),

                "AMOUNT" VARCHAR2(30 BYTE),

                "CIF" NUMBER

   ) SEGMENT CREATION IMMEDIATE

  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255

 NOCOMPRESS LOGGING

  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645

  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1

  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)

  TABLESPACE "SI_DATA" ;

--------------------------------------------------------

--  DDL for Table NCIB_123_SPRINT8_APPROVAL_WORKFLOW_TASKS_ORG_PREPARED_CARD

--------------------------------------------------------

 

  CREATE TABLE "NCIB_123_SPRINT8_APPROVAL_WORKFLOW_TASKS_ORG_PREPARED_CARD"

   (           "INTERNAL_ID" NUMBER,

                "SUBMITTION_DATE" TIMESTAMP (6),

                "REQUEST_TYPE" VARCHAR2(50 BYTE),

                "CARD_NUMBER" VARCHAR2(50 BYTE),

                "APPROVER_MCR_ID" VARCHAR2(20 BYTE),

                "SUBMITTER_MCR_ID" VARCHAR2(20 BYTE),

                "CIF" NUMBER,

                "FROM_ACCOUNT" VARCHAR2(100 BYTE),

                "DECISION_DATE" TIMESTAMP (6),

                "AMOUNT" VARCHAR2(100 BYTE),

                "PAYMENT_MODE" VARCHAR2(100 BYTE),

                "CARD_ACCOUNT_NUMBER" VARCHAR2(100 BYTE),

                "REQUESTED_STATUS" VARCHAR2(100 BYTE),

                "APPROVAL_TASK_STATUS" VARCHAR2(50 BYTE)

   ) SEGMENT CREATION IMMEDIATE

  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255

 NOCOMPRESS LOGGING

  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645

  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1

  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)

  TABLESPACE "SI_DATA" ;

--------------------------------------------------------

--  DDL for Table NCIB_124_SPRINT8_MAKER_CHECKER_WORKFLOW_DEFINITION

--------------------------------------------------------

 

  CREATE TABLE "NCIB_124_SPRINT8_MAKER_CHECKER_WORKFLOW_DEFINITION"

   (           "OPERATION" VARCHAR2(19 BYTE),

                "CIF" VARCHAR2(40 BYTE),

                "APPROVER_USER_ID" VARCHAR2(20 BYTE)

   ) SEGMENT CREATION IMMEDIATE

  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255

 NOCOMPRESS LOGGING

  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645

  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1

  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)

  TABLESPACE "SI_DATA" ;

--------------------------------------------------------

--  DDL for Table NCIB_125_WORKFLOW_INSTANCE

--------------------------------------------------------

 

  CREATE TABLE "NCIB_125_WORKFLOW_INSTANCE"

   (           "APPROVER_USER_ID" VARCHAR2(20 BYTE),

                "APPROVER_USER_NAME" VARCHAR2(20 BYTE),

                "APPROVER_MCR_DIVISION_ID" VARCHAR2(32 BYTE),

                "APPROVER_MRC_DIVISION_NAME" VARCHAR2(988 BYTE),

                "APPRGROUPID" NUMBER(38,0),

                "APPROVAL_GROUP" VARCHAR2(255 BYTE),

                "ITEMID" NUMBER(38,0),

                "BUSINESS_CIF" VARCHAR2(40 BYTE),

                "GROUPORUSERID" NUMBER(38,0),

                "APPROVAL_ID" VARCHAR2(20 BYTE),

                "APPROVINGUSERID" NUMBER(38,0),

                "DECISION" VARCHAR2(16 BYTE),

                "DATE_OF_DECISION" DATE,

                "SUBMITTING_USER_ID" VARCHAR2(20 BYTE),

                "SUBMITTING_USER" NUMBER(38,0),

                "SUBMITTINGUSERNAME" VARCHAR2(107 BYTE),

                "DATE_OF_SUBMITTING" DATE,

                "CORRELATION_ID" VARCHAR2(32 BYTE),

                "TRANSACTIONTYPE" NUMBER(38,0),

                "TRANSACTION_DESCRIPTION" VARCHAR2(40 BYTE),

                "DTSUBMIT" DATE,

                "AMOUNT" VARCHAR2(32 BYTE),

                "CUSTOMER_BUSINESS_NAME" VARCHAR2(250 BYTE),

                "ISUSER" CHAR(1 BYTE)

   ) SEGMENT CREATION IMMEDIATE

  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255

 NOCOMPRESS LOGGING

  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645

  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1

  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)

  TABLESPACE "SI_DATA" ;

--------------------------------------------------------

--  DDL for Table NCIB_127_SPRINT8_APPROVAL_WORKFLOW_TASKS_GOV_EXPENSES_CARD

--------------------------------------------------------

 

  CREATE TABLE "NCIB_127_SPRINT8_APPROVAL_WORKFLOW_TASKS_GOV_EXPENSES_CARD"

   (           "CARD_NUMBER" VARCHAR2(50 BYTE),

                "PAYMENT_MODE" VARCHAR2(100 BYTE),

                "FROM_ACCOUNT" VARCHAR2(100 BYTE),

                "AMOUNT" VARCHAR2(100 BYTE),

                "REQUESTED_STATUS" VARCHAR2(100 BYTE),

                "CIF" NUMBER,

                "SUBMITTER_MCR_ID" VARCHAR2(20 BYTE),

                "SUBMITTION_DATE" TIMESTAMP (6),

                "APPROVER_MCR_ID" VARCHAR2(20 BYTE),

                "REQUEST_TYPE" VARCHAR2(50 BYTE),

                "CARD_ACCOUNT_NUMBER" VARCHAR2(100 BYTE),

                "APPROVAL_TASK_STATUS" VARCHAR2(50 BYTE),

                "DECISION_DATE" TIMESTAMP (6),

                "INTERNAL_ID" NUMBER

   ) SEGMENT CREATION IMMEDIATE

  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255

 NOCOMPRESS LOGGING

  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645

  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1

  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)

  TABLESPACE "SI_DATA" ;

--------------------------------------------------------

--  DDL for Table NCIB_127_SPRINT8_APPROVAL_WORKFLOW_TASKS_GOV_EXPENSES_CARD_2

--------------------------------------------------------

 

  CREATE TABLE "NCIB_127_SPRINT8_APPROVAL_WORKFLOW_TASKS_GOV_EXPENSES_CARD_2"

   (           "CARD_ACCOUNT_NUMBER" VARCHAR2(100 BYTE),

                "REQUESTED_STATUS" VARCHAR2(100 BYTE),

                "CARD_NUMBER" VARCHAR2(50 BYTE),

                "FROM_ACCOUNT" VARCHAR2(100 BYTE),

                "SUBMITTER_MCR_ID" VARCHAR2(20 BYTE),

                "PAYMENT_MODE" VARCHAR2(100 BYTE),

                "CIF" NUMBER,

                "DECISION_DATE" TIMESTAMP (6),

                "AMOUNT" VARCHAR2(100 BYTE),

                "SUBMITTION_DATE" TIMESTAMP (6),

                "APPROVAL_TASK_STATUS" VARCHAR2(50 BYTE),

                "APPROVER_MCR_ID" VARCHAR2(20 BYTE),

                "INTERNAL_ID" NUMBER,

                "REQUEST_TYPE" VARCHAR2(50 BYTE)

   ) SEGMENT CREATION IMMEDIATE

  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255

 NOCOMPRESS LOGGING

  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645

  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1

  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)

  TABLESPACE "SI_DATA" ;

--------------------------------------------------------

--  DDL for Table NCIB_128_SPRINT8_APPROVAL_WORKFLOW_TASKS_GOV_INCOME_TRANSFER

--------------------------------------------------------

 

  CREATE TABLE "NCIB_128_SPRINT8_APPROVAL_WORKFLOW_TASKS_GOV_INCOME_TRANSFER"

   (           "APPROVER_MCR_ID" VARCHAR2(20 BYTE),

                "TO_ACCOUNT_NAME" VARCHAR2(100 BYTE),

                "LETTER_DATE" VARCHAR2(20 BYTE),

                "BANK_CODE" VARCHAR2(20 BYTE),

                "INCOME_PERIOD_TO" VARCHAR2(20 BYTE),

                "CIF" NUMBER,

                "FROM_ACCOUNT" VARCHAR2(30 BYTE),

                "FEES_INFO" BLOB,

                "FT_REFERENCE_NUMBER" VARCHAR2(30 BYTE),

                "LETTER_NUMBER" VARCHAR2(50 BYTE),

                "SUBMITTION_DATE" TIMESTAMP (6),

                "DECISION_DATE" TIMESTAMP (6),

                "AMOUNT" NUMBER,

                "INTERNAL_ID" NUMBER,

                "SUBMITTER_MCR_ID" VARCHAR2(20 BYTE),

                "APPROVAL_TASK_STATUS" VARCHAR2(50 BYTE),

                "TO_ACCOUNT" VARCHAR2(30 BYTE),

                "FINANCIAL_YEAR" VARCHAR2(20 BYTE),

                "INCOME_PERIOD_FROM" VARCHAR2(20 BYTE)

   ) SEGMENT CREATION IMMEDIATE

  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255

 NOCOMPRESS LOGGING

  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645

  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1

  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)

  TABLESPACE "SI_DATA"

 LOB ("FEES_INFO") STORE AS SECUREFILE (

  TABLESPACE "SI_DATA" ENABLE STORAGE IN ROW CHUNK 8192

  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES

  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645

  PCTINCREASE 0

  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

--------------------------------------------------------

--  DDL for Table NCIB_130_SPRINT6_CBC_USERS

--------------------------------------------------------

 

  CREATE TABLE "NCIB_130_SPRINT6_CBC_USERS"

   (           "EMPLOYEE_ID" NUMBER(38,0),

                "USER_NAME" VARCHAR2(18 BYTE),

                "FIRST_NAME" VARCHAR2(35 BYTE),

                "LAST_NAME" VARCHAR2(35 BYTE),

                "EMAIL_ADDRESS" VARCHAR2(40 BYTE),

                "HOME_PHONE" VARCHAR2(14 BYTE),

                "EMPLOYEE_STATUS" VARCHAR2(20 BYTE),

                "LAST_ACTIVE_DATE" TIMESTAMP (6),

                "LAST_LOGIN_DATE" TIMESTAMP (6),

                "SUPERVISOR_GROUP_NAME" VARCHAR2(200 BYTE),

                "SUPERVISOR_GROUP_ID" NUMBER

   ) SEGMENT CREATION IMMEDIATE

  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255

 NOCOMPRESS LOGGING

  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645

  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1

  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)

  TABLESPACE "SI_DATA" ;

--------------------------------------------------------

--  DDL for Table NCIB_131_SPRINT6_CBC_PROFILE_PERMISSIONS

--------------------------------------------------------

 

  CREATE TABLE "NCIB_131_SPRINT6_CBC_PROFILE_PERMISSIONS"

   (           "PK" NUMBER(38,0),

                "CBC_PROFILE" VARCHAR2(255 BYTE),

                "PERMISSION" VARCHAR2(255 BYTE),

                "PERMISSION_DESCRIPTION" VARCHAR2(255 BYTE)

   ) SEGMENT CREATION IMMEDIATE

  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255

 NOCOMPRESS LOGGING

  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645

  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1

  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)

  TABLESPACE "SI_DATA" ;

--------------------------------------------------------

--  DDL for Table NCIB_131_SPRINT6_CBC_USER_PROFILE

--------------------------------------------------------

 

  CREATE TABLE "NCIB_131_SPRINT6_CBC_USER_PROFILE"

   (           "EMPLOYEE_ID" NUMBER(38,0),

                "USER_NAME" VARCHAR2(18 BYTE),

                "ENT_GROUP_ID" NUMBER(38,0),

                "ENT_GROUP_NAME" VARCHAR2(255 BYTE)

   ) SEGMENT CREATION IMMEDIATE

  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255

 NOCOMPRESS LOGGING

  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645

  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1

  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)

  TABLESPACE "SI_DATA" ;

--------------------------------------------------------

--  DDL for Table NCIB_132_SPRINT6_CBC_SUPERVISOUR_GROUP

--------------------------------------------------------

 

  CREATE TABLE "NCIB_132_SPRINT6_CBC_SUPERVISOUR_GROUP"

   (           "EMPLOYEE_ID" NUMBER(38,0),

                "USER_NAME" VARCHAR2(18 BYTE),

                "GROUP_ID" NUMBER,

                "GROUP_NAME" VARCHAR2(200 BYTE)

   ) SEGMENT CREATION IMMEDIATE

  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255

 NOCOMPRESS LOGGING

  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645

  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1

  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)

  TABLESPACE "SI_DATA" ;

--------------------------------------------------------

--  DDL for Table NCIB_135_SPRINT5_TRANSACTIONS_FOR_CONSUMED_LIMITS_EXTRENAL

--------------------------------------------------------

 

  CREATE TABLE "NCIB_135_SPRINT5_TRANSACTIONS_FOR_CONSUMED_LIMITS_EXTRENAL"

   (           "TRANACTION_INTERNAL_ID" VARCHAR2(32 BYTE),

                "CIF" VARCHAR2(40 BYTE),

                "USER_ID" VARCHAR2(20 BYTE),

                "AMOUNT" VARCHAR2(32 BYTE),

                "CURRENCY" VARCHAR2(32 BYTE),

                "FROM_ACCOUNT_NUMBER" VARCHAR2(48 BYTE),

                "PERMISSION_NAME" VARCHAR2(255 BYTE),

                "EXCHANGE_RATE" VARCHAR2(255 BYTE),

                "START_DATE" VARCHAR2(32 BYTE)

   ) SEGMENT CREATION IMMEDIATE

  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255

 NOCOMPRESS LOGGING

  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645

  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1

  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)

  TABLESPACE "SI_DATA" ;

--------------------------------------------------------

--  DDL for Table NCIB_135_SPRINT5_TRANSACTIONS_FOR_CONSUMED_LIMITS_MY_ACCOUNT

--------------------------------------------------------

 

  CREATE TABLE "NCIB_135_SPRINT5_TRANSACTIONS_FOR_CONSUMED_LIMITS_MY_ACCOUNT"

   (           "TRANSACTION_INTERNAL_ID" VARCHAR2(32 BYTE),

                "CIF" VARCHAR2(40 BYTE),

                "USER_ID" VARCHAR2(20 BYTE),

                "AMOUNT" VARCHAR2(32 BYTE),

                "CURRENCY" VARCHAR2(3 BYTE),

                "FROM_ACCOUNT_NUMBER" VARCHAR2(48 BYTE),

                "PERMISSION_NAME" CHAR(20 BYTE),

                "EXCHANGE_RATE" VARCHAR2(255 BYTE),

                "START_DATE" VARCHAR2(32 BYTE)

   ) SEGMENT CREATION DEFERRED

  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255

 NOCOMPRESS LOGGING

  TABLESPACE "SI_DATA" ;

--------------------------------------------------------

--  DDL for Table NCIB_137_SPRINT8_APPROVAL_WORKFLOW_TASKS_STANDING_ORDER

--------------------------------------------------------

 

  CREATE TABLE "NCIB_137_SPRINT8_APPROVAL_WORKFLOW_TASKS_STANDING_ORDER"

   (           "TARGET_ACCOUNT_NUMBER" VARCHAR2(50 BYTE),

                "ACCOUNT_CATEGORY" VARCHAR2(50 BYTE),

                "FREQUANCY" VARCHAR2(50 BYTE),

                "INTERNAL_ID" NUMBER,

                "FROM_ACCOUNT" VARCHAR2(50 BYTE),

                "APPROVAL_TASK_STATUS" VARCHAR2(50 BYTE),

                "TRANSFER_CURRENCY" VARCHAR2(50 BYTE),

                "PAYMENT_DESCRIPTION" VARCHAR2(140 BYTE),

                "DECISION_DATE" TIMESTAMP (6),

                "CIF" NUMBER,

                "SUBMITTER_MCR_ID" VARCHAR2(20 BYTE),

                "EXCHANGE_RATE" VARCHAR2(50 BYTE),

                "STANDING_ORDER_START_DATE" VARCHAR2(50 BYTE),

                "APPROVER_MCR_ID" VARCHAR2(20 BYTE),

                "EXPIRE_DATE" VARCHAR2(50 BYTE),

                "BENE_CODE" VARCHAR2(50 BYTE),

                "SUBMITTION_DATE" TIMESTAMP (6),

                "TRANSFER_PURPOSE" VARCHAR2(100 BYTE),

                "USER_ACTION" VARCHAR2(50 BYTE),

                "AMOUNT" NUMBER

   ) SEGMENT CREATION IMMEDIATE

  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255

 NOCOMPRESS LOGGING

  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645

  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1

  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)

  TABLESPACE "SI_DATA" ;

--------------------------------------------------------

--  DDL for Table NCIB_138_SPRINT6_TRANFER_HISTORY_EXTRENAL

--------------------------------------------------------

 

  CREATE TABLE "NCIB_138_SPRINT6_TRANFER_HISTORY_EXTRENAL"

   (           "STATUS" VARCHAR2(32 BYTE),

                "INTERNAL_ID" VARCHAR2(32 BYTE),

                "CIF" VARCHAR2(40 BYTE),

                "USER_ID" VARCHAR2(20 BYTE),

                "AMOUNT" VARCHAR2(32 BYTE),

                "CURRENCY" VARCHAR2(32 BYTE),

                "ACCOUNT_NUMBER" VARCHAR2(48 BYTE),

                "CUSTOMERID" VARCHAR2(32 BYTE),

                "OPERATION_NAME" VARCHAR2(255 BYTE),

                "EXCHANGE_RATE" VARCHAR2(255 BYTE),

                "TRANSACTION_DATE" VARCHAR2(32 BYTE)

   ) SEGMENT CREATION IMMEDIATE

  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255

 NOCOMPRESS LOGGING

  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645

  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1

  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)

  TABLESPACE "SI_DATA" ;

--------------------------------------------------------

--  DDL for Table NCIB_138_SPRINT6_TRANFER_HISTORY_MY_ACCOUNTS

--------------------------------------------------------

 

  CREATE TABLE "NCIB_138_SPRINT6_TRANFER_HISTORY_MY_ACCOUNTS"

   (           "ACCOUNT_NUMBER" VARCHAR2(48 BYTE),

                "CUSTOMERID" VARCHAR2(32 BYTE),

                "PERMISSION_NAME" CHAR(20 BYTE),

                "EXCHANGE_RATE" VARCHAR2(255 BYTE),

                "TRANSACTION_DATE" VARCHAR2(32 BYTE),

                "STATUS" VARCHAR2(32 BYTE),

                "INTERNAL_ID" VARCHAR2(32 BYTE),

                "CIF" VARCHAR2(40 BYTE),

                "USER_ID" VARCHAR2(20 BYTE),

                "AMOUNT" VARCHAR2(32 BYTE),

                "CURRENCY" VARCHAR2(3 BYTE)

   ) SEGMENT CREATION DEFERRED

  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255

 NOCOMPRESS LOGGING

  TABLESPACE "SI_DATA" ;

--------------------------------------------------------

--  DDL for Table NCIB_141_SPRINT9_BC_USER_LOG

--------------------------------------------------------

 

  CREATE TABLE "NCIB_141_SPRINT9_BC_USER_LOG"

   (           "USER_NAME" VARCHAR2(18 BYTE),

                "ACTION_DESCRIPTION" VARCHAR2(1000 BYTE),

                "BUSINESS_ID" NUMBER(38,0),

                "TRANACTION_TIMESTAMP" TIMESTAMP (6),

                "ACTION_ON_CIF" VARCHAR2(40 BYTE)

   ) SEGMENT CREATION IMMEDIATE

  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255

 NOCOMPRESS LOGGING

  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645

  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1

  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)

  TABLESPACE "SI_DATA" ;

--------------------------------------------------------

--  DDL for Table NCIB_141_SPRINT9_CIB_USER_LOG

--------------------------------------------------------

 

  CREATE TABLE "NCIB_141_SPRINT9_CIB_USER_LOG"

   (           "BUSINESS_CIF" VARCHAR2(40 BYTE),

                "LOG_DATE" TIMESTAMP (6),

                "ACTION_DESCRIPTION" VARCHAR2(100 BYTE),

                "ACTION_BY_USER" VARCHAR2(20 BYTE),

                "INTEGRATION_FUNCTION_ID" VARCHAR2(40 BYTE),

                "AMOUNT_IF_TRANSACTION" NUMBER(31,3),

                "CURRENCY" VARCHAR2(3 BYTE),

                "TRANSACTION_STATUS" VARCHAR2(32 BYTE),

                "PARAMTER_0" VARCHAR2(4000 BYTE),

                "PARAMTER_1" VARCHAR2(4000 BYTE),

                "PARAMTER_3" VARCHAR2(4000 BYTE),

                "PARAMTER_4" VARCHAR2(4000 BYTE)

   ) SEGMENT CREATION IMMEDIATE

  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255

 NOCOMPRESS LOGGING

  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645

  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1

  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)

  TABLESPACE "SI_DATA" ;

--------------------------------------------------------

--  DDL for Table NCIB_93_PERMISSION_ENTITY_CONFIRMED

--------------------------------------------------------

 

  CREATE TABLE "NCIB_93_PERMISSION_ENTITY_CONFIRMED"

   (           "OPERATION_NAME" VARCHAR2(255 BYTE),

                "PARENT_OPERATION" VARCHAR2(255 BYTE),

                "PERMISION_PER_COMPANY" NUMBER,

                "PERMISION_PER_GROUP" NUMBER,

                "PERMISION_PER_USER" NUMBER,

                "PERMISION_PER_ACCOUNT" NUMBER,

                "PERMISION_CROSS_ACCOUNT" NUMBER,

                "PERMISSION_BC_EMPLOYEE" NUMBER,

                "LIMITABLE" NUMBER

   ) SEGMENT CREATION IMMEDIATE

  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255

 NOCOMPRESS LOGGING

  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645

  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1

  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)

  TABLESPACE "SI_DATA" ;

--------------------------------------------------------

--  DDL for Table NCIB_94_EXCLUDED_PERMISSIONS_CONFIRMED

--------------------------------------------------------

 

  CREATE TABLE "NCIB_94_EXCLUDED_PERMISSIONS_CONFIRMED"

   (           "OPERATION_NAME" VARCHAR2(255 BYTE)

   ) SEGMENT CREATION IMMEDIATE

  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255

 NOCOMPRESS LOGGING

  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645

  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1

  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)

 TABLESPACE "SI_DATA" ;

--------------------------------------------------------

--  DDL for Table NCIB_96_CUSTOMER_SERVICE_PACKAGE_CONFIRMED

--------------------------------------------------------

 

  CREATE TABLE "NCIB_96_CUSTOMER_SERVICE_PACKAGE_CONFIRMED"

   (           "CIF" VARCHAR2(40 BYTE),

                "SERVICE_PACKAGE_NAME" VARCHAR2(255 BYTE),

                "INTERNAL_ENTITLEMENT_GROUP_ID" NUMBER(38,0)

   ) SEGMENT CREATION IMMEDIATE

  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255

 NOCOMPRESS LOGGING

  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645

  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1

  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)

  TABLESPACE "SI_DATA" ;

--------------------------------------------------------

--  DDL for Table NCIB_96_SERVICE_PACKAGE_CONFIRMED

--------------------------------------------------------

 

  CREATE TABLE "NCIB_96_SERVICE_PACKAGE_CONFIRMED"

   (           "SERVICE_PACKAGE_NAME" VARCHAR2(255 BYTE),

                "SERVICE_PACKAGE_INTERNAL_ID" NUMBER(38,0),

                "DESCRIPTION" VARCHAR2(255 BYTE)

   ) SEGMENT CREATION IMMEDIATE

  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255

 NOCOMPRESS LOGGING

  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645

  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1

  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)

  TABLESPACE "SI_DATA" ;

--------------------------------------------------------

--  DDL for Table NCIB_97_BANKING_ACCOUNTS_ACCESSABLE_ONLINE_CONFIRMED

--------------------------------------------------------

 

  CREATE TABLE "NCIB_97_BANKING_ACCOUNTS_ACCESSABLE_ONLINE_CONFIRMED"

   (           "BANKING_ACCOUNT_NUMBER" VARCHAR2(48 BYTE),

                "CIF" VARCHAR2(40 BYTE)

   ) SEGMENT CREATION IMMEDIATE

  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255

 NOCOMPRESS LOGGING

  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645

  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1

  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)

  TABLESPACE "SI_DATA" ;

--------------------------------------------------------

--  DDL for Table NCIB_97_CUSTOMER_CREATION_HISTORY

--------------------------------------------------------

 

  CREATE TABLE "NCIB_97_CUSTOMER_CREATION_HISTORY"

   (           "CUSTOMER_BUSINESS_NAME" VARCHAR2(200 BYTE),

                "CIF" VARCHAR2(40 BYTE),

                "CORP_LOGIN_NAME" VARCHAR2(20 BYTE),

                "INTERNAL_ID" NUMBER(38,0),

                "APPROVED_BY_USER_ID" NUMBER(38,0),

                "MAIN_USER_ID" VARCHAR2(20 BYTE),

                "BUSINESS_STATUS" VARCHAR2(32 BYTE),

                "DIRECTORY_ID" NUMBER(38,0),

                "CUST_ID" VARCHAR2(20 BYTE),

                "DIRECTORY_DATE" DATE,

                "LAST_ACTIVE_DATE" DATE,

                "ACCOUNT_STATUS" NUMBER(38,0),

                "CREATE_DATE" TIMESTAMP (6),

                "MODIFIED_DATE" DATE,

                "ACTIVATION_DATE" DATE,

                "APPROVED_BY_USERNAME" VARCHAR2(18 BYTE)

   ) SEGMENT CREATION IMMEDIATE

  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255

 NOCOMPRESS LOGGING

  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645

  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1

  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)

  TABLESPACE "SI_DATA" ;

--------------------------------------------------------

--  DDL for Table NCIB_97_CUSTOMER_PROFILE_CONFIRMED

--------------------------------------------------------

 

  CREATE TABLE "NCIB_97_CUSTOMER_PROFILE_CONFIRMED"

   (           "CIF" VARCHAR2(40 BYTE),

                "CORP_LOGIN_NAME" VARCHAR2(20 BYTE),

                "INTERNAL_ID" NUMBER(38,0),

                "MAIN_USER_ID" VARCHAR2(20 BYTE),

                "BUSINESS_STATUS" VARCHAR2(32 BYTE),

                "APPROVED_BY_USERNAME" VARCHAR2(18 BYTE),

                "APPROVED_BY_USER_ID" NUMBER(38,0)

   ) SEGMENT CREATION IMMEDIATE

  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255

 NOCOMPRESS LOGGING

  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645

  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1

  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)

  TABLESPACE "SI_DATA" ;

--------------------------------------------------------

--  DDL for Table NCIB_CUSTOMER_WHITELIST

--------------------------------------------------------

 

  CREATE TABLE "NCIB_CUSTOMER_WHITELIST"

   (           "CIF" VARCHAR2(1000 BYTE),

                "SERVICE_PACKAGE_ID" VARCHAR2(1000 BYTE)

   ) SEGMENT CREATION IMMEDIATE

  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255

 NOCOMPRESS LOGGING

  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645

  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1

  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)

  TABLESPACE "SI_DATA" ;